app/config/urls.py
from django.contrib import admin
from django.urls import path, include
#from core.homepage.views import IndexView
from core.login.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    #path('', IndexView.as_view(), name='index'),
    path('', LoginFormView.as_view(), name='login'),
    path('admin/', admin.site.urls),
    path('erp/', include('core.erp.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/erp/urls.py
from django.urls import path
from django.contrib.auth.views import  LogoutView
from core.erp.views.puntos_avitar.views import *
from core.erp.views.inicio_avitar.views import *
from core.erp.views.inmuebles.views import *
from core.erp.views.pqrs.views import *
from core.erp.views.mantenimientos.views import *
from core.erp.views.reportes.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static

app_name = 'erp'
urlpatterns = [
    #salir
    path('salir',LogoutView.as_view(next_page='login'),name='salir'),
    # home
    path('inicio',inicioCreateView.as_view(), name='inicio'),
    #puntaje
    path('list/<int:id>/<str:nom>',PuntajeListView.as_view(), name='list'),
    path('ventas',VentasListView.as_view(), name='ventas'),
    path('list_general',GeneralListView.as_view(), name='list_general'),
    path('list_general/delete/<int:pk>/', SaleDeleteView.as_view(), name='sale_delete'),
    #inmuebles
    path('inmueble',InmuebleCreateView.as_view(), name='inmueble'),
    path('inmuebleedit/<int:pk>/',InmuebleUpdateView.as_view(), name='inmuebleedit'),
    path('contratoedit/<int:pk>/',AdministracionUpdateView.as_view(), name='inmuebleedit'),
    path('fichamodal',fichamodalListView.as_view(), name='fichamodal'),
    path('tipos',tipo_clienteCreateView.as_view(), name='tipos'),
    path('ubicacion',ubicacionCreateView.as_view(), name='ubicacion'),
    path('clientes',clientesCreateView.as_view(), name='clientes'),
    path('tipoinmueble',tipoinmuebleCreateView.as_view(), name='tipoinmueble'),
    path('servicios',serviciosCreateView.as_view(), name='servicios'),
    path('administracionlist',AdministracionListView.as_view(), name='administracionlist'),
    path('corretajelist',CorretajeListView.as_view(), name='corretajelist'),
    path('arrendamientolist',ArrendamientoListView.as_view(), name='arrendamientolist'),
    #PRS
    path('pqrslist',pqrsListView.as_view(), name='pqrslist'),
    
    #mantenimientos
    path('novedadeslist',novedadListView.as_view(), name='novedadeslist'),
    path('mantenimientoslist',mantenimientosListView.as_view(), name='mantenimientoslist'),
    path('individual/<int:id>/<str:action>',mantenimientosListView1.as_view(), name='individual'),
    path('detalle/<int:id>',detallesListView.as_view(),name='detalle'),
    path('preventivos',fichaListView.as_view(),name='preventivos'),
    path('procedimiento',procedimientoCreateView.as_view(), name='procedimiento'),
   #reportes
    path('list/reporteclientePDF/<int:id>',InformeclientesPDFView.as_view(),name='reporteclientePDF'),
    path('detalle/reportePDF/<int:id>' ,InformePDFView.as_view(),name='reportePDF'),
    path('ventas/reporteventasPDF/<str:init>/<str:end>' ,InformeventasPDFView.as_view(),name='reporteventasPDF'),
    path('reportenovedadPDF/<str:estado>/<str:init>/<str:end>' ,InformenovedadPDFView.as_view(),name='reportenovedadPDF'),
    path('reportemantenimientoPDF/<str:estado>/<str:init>/<str:end>' ,InformemantenimientoPDFView.as_view(),name='reportemantenimientoPDF'),
    path('fichaPDF/<int:id>' ,FichaTecnicaPDFView.as_view(),name='fichaPDF'),
    path('adminPDF/<int:id>' ,ContratoAdminPDFView.as_view(),name='adminPDF'),
    path('corretajePDF/<int:id>' ,ContratoCorretajePDFView.as_view(),name='corretajePDF'),
    path('arrendamientoPDF/<int:id>' ,ContratoArendamientoPDFView.as_view(),name='arrendamientoPDF'),
    path('constructorPDF/<int:id>' ,ConstructorPDFView.as_view(),name='constructorPDF'),
    path('reporteinmueblesPDF/<str:estatus>/<str:contrato>' ,InformeinmueblesPDFView.as_view(),name='reporteinmueblesPDF'),
    
    #path('tipos',tipo_clienteCreateView.as_view(), name='tipos'),
      
   
   
   
   
    #path('fichalist',fichaListView.as_view(),name='fichalist'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/hzt/body.html
{% extends 'home.html' %}
{% block body %}
    <body class="hold-transition layout-top-nav">
    <div class="wrapper">
        <!-- Header -->
        {% include 'hzt/header.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> Bienvenido <small>{{ request.user.get_full_name }}</small></h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{ list }}">{{ entity }}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}
      
    {% endblock %}
    <script>
        {% if messages %}
            var html = '<p>';
            {% for message in messages %}
                html += '{{ message }}<br>';
            {% endfor %}
            html += '</p>';
            Swal.fire({
                title: 'Error!',
                html: html,
                icon: 'error'
            });
        {% endif %}
    </script>
    </body>
{% endblock %}

app/templates/hzt/header.html
{% load static %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-dark navbar-primary">
    <div class="container">
        <a href="" class="navbar-brand">
            {% if "Ferreteria" == request.user.groups.all.0.name  %}
            <img src="{% static 'img/logo avitar FERRETERIA.png' %}" alt="AdminLTE Logo"
                 class="brand-image"
                 >
            {% else %}
            <img src="{% static 'img/LogoBlanco.png' %}" alt="AdminLTE Logo"
            class="brand-image"
            >                     
            {% endif %}     
            
            
            
        </a>
        <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse order-3" id="navbarCollapse">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{% url 'erp:inicio' %}" class="nav-link"><i class="fas fa-home"></i> Home</a>
                </li>
                
                <li class="nav-item dropdown">
                    <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                       class="nav-link dropdown-toggle"><i class="fas fa-folder-open"></i> Mantenimientos</a>
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                        <li><a href="{% url 'erp:pqrslist' %}" class="dropdown-item"><i class="fas fa-truck-loading"></i> Operaciones</a></li>
                        
                       
                    </ul>
                </li>
                
                <li class="nav-item dropdown">
                    <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                       class="nav-link dropdown-toggle"><i class="fas fa-folder-open"></i> Inmuebles</a>
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                        <li><a href="{% url 'erp:fichamodal' %}" class="dropdown-item"><i class="fas fa-truck-loading"></i> Listado Inmuebles</a></li>
                        <li><a href="{% url 'erp:inmueble' %}" class="dropdown-item"><i class="fas fa-boxes"></i> Nuevo Inmueble</a></li>
                        <li><a href="{% url 'erp:administracionlist' %}" class="dropdown-item"><i class="fas fa-boxes"></i> Contratos</a></li>
                    </ul>
                </li>
                
                <li class="nav-item dropdown">
                    <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                       class="nav-link dropdown-toggle"><i class="fas fa-folder-open"></i> Ferreteria</a>
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                        <li><a href="{% url 'erp:ventas' %}" class="dropdown-item"><i class="fas fa-shopping-cart"></i> Puntos Avitar</a></li>
                        <li><a href="{% url 'erp:list_general' %}" class="dropdown-item"><i class="fas fa-shopping-cart"></i> Facturas</a></li>
                    </ul>
                </li>
            </ul>
            
        </div>
        <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    {% for g in request.user.groups.all %}

                    <i class="fas fa-users-cog"></i> {{ g.name }}
                </a>
                {% endfor %}
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header" style="font-size: 12px;">
                        Sú último acceso fue {{ request.user.last_login }}
                    </span>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-edit mr-2"></i> Editar perfil
                        <span class="float-right text-muted text-sm">3 mins</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-lock mr-2"></i> Editar password
                        <span class="float-right text-muted text-sm">12 hours</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">
                        <p>Este sistema te permitira realizar diferentes actividades</p>
                    </a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'erp:salir' %}">
                    <i class="fas fa-power-off" aria-hidden="true"></i>
                </a>
            </li>
        </ul>
    </div>
</nav>